name: Docker Image CI

on:
  push:
    tags:
      - '*'
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
#     - name: Build the Docker image
    - name: Set env
      run: 
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
#       run: echo "hello tag"
